[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "source /opt/venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT" 